# Generated by Django 6.0.4 on 2026-08-02 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0013_washingstation_coffeelot_washing_station_facility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('roasting', 'Roasting'), ('resting', 'Resting'), ('qc', 'Quality Check'), ('packaged', 'Packaged'), ('shipped', 'Shipped')], default='queued', max_length=20)),
                ('roast_date', models.DateField(blank=True, null=True)),
                ('roast_level', models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('medium_dark', 'Medium-Dark'), ('dark', 'Dark')], max_length=20)),
                ('charge_temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('drop_temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('first_crack_time_s', models.PositiveIntegerField(blank=True, null=True)),
                ('development_time_s', models.PositiveIntegerField(blank=True, null=True)),
                ('output_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('qc_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qc_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roaster', models.ForeignKey(limit_choices_to={'role': 'roaster'}, on_delete=django.db.models.deletion.CASCADE, related_name='roast_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoastBatchLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_inputs', to='roasting.roastbatch')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roast_batch_uses', to='lots.coffeelot')),
            ],
            options={
                'ordering': ['lot__lot_id'],
            },
        ),
        migrations.CreateModel(
            name='RoastEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('machine_type', models.CharField(choices=[('drum', 'Drum Roaster'), ('fluid_bed', 'Fluid Bed Roaster'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='drum', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('batch_capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roaster', models.ForeignKey(limit_choices_to={'role': 'roaster'}, on_delete=django.db.models.deletion.CASCADE, related_name='roast_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roast Equipment',
                'verbose_name_plural': 'Roast Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='roastbatch',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='roasting.roastequipment'),
        ),
        migrations.AlterUniqueTogether(
            name='roastbatch',
            unique_together={('roaster', 'batch_code')},
        ),
    ]
