#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

export PATH="/app/.venv/bin:$PATH"
export PYTHONPATH="/app/.venv/lib/python3.14/site-packages:/app"

python manage.py migrate
exec python manage.py runserver_plus 0.0.0.0:8000
