# Generated by Django 6.0.4 on 2026-05-05 19:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('listed', 'Listed'), ('contracted', 'Contracted'), ('exported', 'Exported')], default='draft', max_length=20)),
                ('region', models.CharField(choices=[('yirgacheffe', 'Yirgacheffe'), ('sidama', 'Sidama'), ('guji', 'Guji'), ('jimma', 'Jimma'), ('harrar', 'Harrar'), ('limu', 'Limu'), ('nekemte', 'Nekemte'), ('other', 'Other')], max_length=50)),
                ('kebele', models.CharField(blank=True, max_length=200)),
                ('washing_station', models.CharField(blank=True, max_length=200)),
                ('altitude_m', models.IntegerField()),
                ('processing', models.CharField(choices=[('washed', 'Washed'), ('natural', 'Natural'), ('honey', 'Honey')], max_length=20)),
                ('grade', models.CharField(choices=[('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3')], max_length=5)),
                ('varietal', models.CharField(default='Ethiopian Heirloom', max_length=200)),
                ('harvest_date', models.DateField()),
                ('farm_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('farm_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('sca_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('flavor_notes', models.CharField(blank=True, max_length=500)),
                ('cupping_date', models.DateField(blank=True, null=True)),
                ('q_grader_name', models.CharField(blank=True, max_length=200)),
                ('q_grader_cert_id', models.CharField(blank=True, max_length=100)),
                ('deforestation_free', models.BooleanField(default=False)),
                ('gps_verified', models.BooleanField(default=False)),
                ('phyto_cert_uploaded', models.BooleanField(default=False)),
                ('ecta_license_active', models.BooleanField(default=False)),
                ('nbe_fx_declared', models.BooleanField(default=False)),
                ('cta_floor_met', models.BooleanField(default=False)),
                ('eudr_dds_ready', models.BooleanField(default=False)),
                ('phyto_cert_file', models.FileField(blank=True, null=True, upload_to='lots/phyto/')),
                ('eudr_dds_file', models.FileField(blank=True, null=True, upload_to='lots/dds/')),
                ('volume_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coffee Lot',
                'verbose_name_plural': 'Coffee Lots',
                'ordering': ['-created_at'],
            },
        ),
    ]
