# Generated by Django 6.0.4 on 2026-05-07 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuppingScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('fragrance_aroma', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('flavor', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('aftertaste', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('acidity', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('body', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('balance', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('uniformity', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('clean_cup', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('sweetness', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('overall', models.DecimalField(decimal_places=2, help_text='6–10', max_digits=4)),
                ('defects', models.DecimalField(decimal_places=2, default=0, help_text='Penalty points', max_digits=4)),
                ('flavor_notes', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True, help_text='Private Q-Grader notes')),
                ('cupping_date', models.DateField()),
                ('cupping_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupping_scores', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupping_scores', to='lots.coffeelot')),
            ],
            options={
                'verbose_name': 'Cupping Score',
                'verbose_name_plural': 'Cupping Scores',
                'ordering': ['-cupping_date', '-created_at'],
            },
        ),
    ]
