# Generated by Django 6.0.4 on 2026-05-18 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_cuppingscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('received', 'Received')], default='pending', max_length=20)),
                ('quantity_g', models.IntegerField(default=200, help_text='Sample size in grams')),
                ('message', models.TextField(blank=True, help_text='Message from buyer')),
                ('response', models.TextField(blank=True, help_text='Response from exporter')),
                ('shipping_address', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_requests', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_requests', to='lots.coffeelot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
