# Generated by Django 6.0.4 on 2026-05-22 11:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_samplerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeelot',
            name='farm_polygon',
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, help_text='Lot boundary polygon — overrides farm polygon if set', null=True, srid=4326),
        ),
    ]
