# Generated by Django 6.0.4 on 2026-05-23 12:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_remove_coffeelot_farm_polygon_coffeelot_boundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeforestationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('year', models.IntegerField(help_text='Year deforestation was detected')),
                ('source', models.CharField(default='Hansen GFC', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('area_ha', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='lots_defore_year_220c86_idx')],
            },
        ),
    ]
