# Generated by Django 6.0.4 on 2026-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeelot',
            name='customs_declaration_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='ecex_permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='ecex_permit_file',
            field=models.FileField(blank=True, null=True, upload_to='lots/ecex/'),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='ecex_permit_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='phyto_cert_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
