# Generated by Django 6.0.4 on 2026-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0007_document_system_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeelot',
            name='customs_declaration_file',
            field=models.FileField(blank=True, null=True, upload_to='lots/customs/'),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='nbe_fx_declaration_file',
            field=models.FileField(blank=True, null=True, upload_to='lots/nbe/'),
        ),
    ]
