# Generated by Django 6.0.4 on 2026-06-06 10:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0008_coffeelot_customs_declaration_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuppingscore',
            options={'ordering': ['-cupping_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='available_qty_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='delivery_window',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='farm_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='farm_story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='flavor_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='fob_price_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='is_fair_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='is_rainforest_alliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='lot_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('forward', 'Forward Contract'), ('reserve', 'Reserve')], default='spot', max_length=20),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='min_order_kg',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='tasting_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coffeelot',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, help_text='Lot boundary polygon', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='coffeelot',
            name='processing',
            field=models.CharField(choices=[('washed', 'Washed'), ('natural', 'Natural'), ('honey', 'Honey'), ('anaerobic', 'Anaerobic'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='acidity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='aftertaste',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='body',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='clean_cup',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='defects',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='flavor',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='fragrance_aroma',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='overall',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='sweetness',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cuppingscore',
            name='uniformity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lot_status', 'Lot Status Change'), ('sample_request', 'Sample Request'), ('eudr_alert', 'EUDR Alert'), ('offer', 'Offer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='samplerequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='samplerequest',
            name='quantity_g',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='samplerequest',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('delivery_window', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('counter_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('counter_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exporter_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='lots.coffeelot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
