# Generated by Django 6.0.4 on 2026-07-27 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_marketplace_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeelot',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='The farmer/cooperative that produced this lot.', limit_choices_to={'role': 'farmer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_produced', to=settings.AUTH_USER_MODEL),
        ),
    ]
