# Generated by Django 6.0.4 on 2026-07-27 19:26

import bunna_bridge.lots.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0011_backfill_farm_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeelot',
            name='customs_declaration_file',
            field=models.FileField(blank=True, null=True, upload_to='lots/customs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), bunna_bridge.lots.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='coffeelot',
            name='ecex_permit_file',
            field=models.FileField(blank=True, null=True, upload_to='lots/ecex/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), bunna_bridge.lots.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='coffeelot',
            name='eudr_dds_file',
            field=models.FileField(blank=True, null=True, upload_to='lots/dds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), bunna_bridge.lots.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='coffeelot',
            name='nbe_fx_declaration_file',
            field=models.FileField(blank=True, null=True, upload_to='lots/nbe/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), bunna_bridge.lots.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='coffeelot',
            name='phyto_cert_file',
            field=models.FileField(blank=True, null=True, upload_to='lots/phyto/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), bunna_bridge.lots.validators.validate_document_size]),
        ),
    ]
