# Generated by Django 6.0.4 on 2026-08-02 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0012_alter_coffeelot_customs_declaration_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, choices=[('yirgacheffe', 'Yirgacheffe'), ('sidama', 'Sidama'), ('guji', 'Guji'), ('jimma', 'Jimma'), ('harrar', 'Harrar'), ('limu', 'Limu'), ('nekemte', 'Nekemte'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, help_text='Kebele / village detail.', max_length=200)),
                ('capacity_kg_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role__in': ['exporter', 'roaster']}, on_delete=django.db.models.deletion.CASCADE, related_name='washing_stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Washing Station',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='coffeelot',
            name='washing_station_facility',
            field=models.ForeignKey(blank=True, help_text='Structured washing station. When set, its name overwrites washing_station on save.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='lots.washingstation'),
        ),
    ]
