services:
  docs:
    image: bunna_bridge_local_docs
    container_name: bunna_bridge_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bunna_bridge:/app/bunna_bridge:z
    ports:
      - '9000:9000'
    command: /start-docs
