# Generated by Django 6.0.4 on 2026-05-22 11:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cooperative_user_farm_altitude_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, help_text='Farm boundary polygon (GPS, WGS84)', null=True, srid=4326),
        ),
    ]
