# Generated by Django 6.0.4 on 2026-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecta_license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ecta_license_file',
            field=models.FileField(blank=True, null=True, upload_to='users/ecta/'),
        ),
        migrations.AddField(
            model_name='user',
            name='ecta_license_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
