# Generated by Django 6.0.4 on 2026-07-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ecta_license_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farm_id',
            field=models.CharField(blank=True, db_index=True, help_text='Permanent Beersheba Farm ID, auto-generated for farmer accounts.', max_length=30, null=True, unique=True),
        ),
    ]
