# Generated by Django 6.0.4 on 2026-07-27 19:27

import bunna_bridge.lots.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_farm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ecta_license_file',
            field=models.FileField(blank=True, null=True, upload_to='users/ecta/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), bunna_bridge.lots.validators.validate_document_size]),
        ),
    ]
