# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_ecta_license_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('exporter', 'Exporter'), ('buyer', 'Buyer'), ('farmer', 'Farmer'), ('qgrader', 'Q-Grader'), ('roaster', 'Roaster')], default='exporter', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='roastery_type',
            field=models.CharField(blank=True, choices=[('micro', 'Micro-roastery (under 500kg/month)'), ('commercial', 'Commercial roastery'), ('cafe', 'Café with in-house roasting'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='roastery_monthly_capacity_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roastery_roast_styles',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g. 'light, medium, dark'.", max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='roastery_preferred_origins',
            field=models.CharField(blank=True, help_text="Comma-separated regions of sourcing interest, e.g. 'Yirgacheffe, Guji'.", max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='roastery_established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roastery_website',
            field=models.URLField(blank=True),
        ),
    ]
