# Generated by Django 6.0.4 on 2026-08-02 15:18

import bunna_bridge.lots.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_roaster_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_type', models.CharField(choices=[('organic', 'Organic'), ('fair_trade', 'Fair Trade'), ('rainforest_alliance', 'Rainforest Alliance'), ('utz', 'UTZ'), ('q_arabica', 'Q Arabica'), ('iso', 'ISO'), ('haccp', 'HACCP'), ('other', 'Other')], max_length=30)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('cert_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), bunna_bridge.lots.validators.validate_document_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['-created_at'],
            },
        ),
    ]
